### ISSUE TITLE
How should I add it to the Chrome Extensions

### ISSUE THREAD

**Issue by richardaum** [myTerminal/template-chrome-extension-webpack#1]
When running it using `npm run live`, how should I add it to the Chrome Extensions?

**Comment by myTerminal** [comment]
As it turns out, in `live` mode, the code will supposedly only run in a web-browser.
As there are no physical files/bundles/assets generated by the webpack-dev-server, I doubt one will be able to test their implementation by loading bundled code as a Chrome extension.

How I take it, I only use `live` mode for developing the UI, so that I can quickly see the changes I make. But to test whether something works, unfortunately I fall back to `develop` mode where I have physical output available on my file-system.

It would be interesting though to learn how and if we can do that, feel free to enlighten me :)

**Comment by myTerminal** [comment]
Closing this one as the query seems to be resolved. Feel free to re-open if required.

**Comment by richardlopes-daitangroup** [comment]
Thanks @myTerminal
